#####
avatar: 
favicon: 
preload: true #字体预加载
excerpt_length: 300 #自动生成的摘要长度 建议文章中手动使用 <!--more--> 效果更佳  
tag_page_count: true #Tag页是否计数
mourn_mode: false #哀悼模式

# 主题颜色
theme_color:
  primary: teal 
  accent: blue

# 搜索
search:
  local: true
  path: /search.xml
  placeholder: 请输入关键字

# Google Adsense广告代码
google_adsense:
  enabled: false #开启广告

#####文章#####
# 文末结束语
passage_end_tag:
  enabled: false

# 数学公式渲染
math:
  enabled: true
  engine: mathjax ##可选渲染引擎：mathjax、katex
  mathjax:
    cdn: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    mhchem: true  #化学式扩展
  katex:
    cdn_css: https://cdn.jsdelivr.net/npm/katex@0.11.1/dist/katex.min.css
    cdn_js: https://cdn.jsdelivr.net/npm/katex@0.11.1/dist/katex.min.js
    auto_render: https://cdn.jsdelivr.net/npm/katex@0.11.1/dist/contrib/auto-render.min.js

# mermaid图
mermaid:
  enable: false
##########

#####侧边栏#####
# 菜单
menu:
  home: / || icon-home
  tags: /tags/ || icon-bookmark
  about: /about/ || icon-user
  #gallery: /categories/图集/ || icon-gallery

# 社交链接
social:
  E-Mail: mailto:qian.wang@nlpr.ia.ac.cn || icon-mail
  GitHub: https://github.com/voidmagic || icon-github
  # 此外还预置了以下社交图标，可直接仿照格式进行引用，如需其他图标请自行添加图标库或与我联系
  # icon-twitter、icon-facebook、icon-vk、icon-stack-overflow、icon-youtube、icon-Instagram、icon-skype
  # icon-qq、icon-wechat、icon-alipay、icon-paypal、icon-telegram、icon-twitch、icon-discord


##########

#####页脚#####
# 页脚
footer:
  since: 2015
  powered: true
  theme: true
  beian:
    enable: true
    icp: 
  icon:
    enabled: true
    name: icon-heart
    color: "#d9333f"

# 不蒜子计数
busuanzi:
  site: false
  page: false
##########

#####第三方服务#####
# 评论
comment:
  enable: false

# 分析
analytics:
  google_analytics:
    tracking_id: 
    localhost_ignored: true
  baidu_site_id:
  cnzz_site_id:
  tencent_site_id:
##########